// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsgFDdKKHEBQ8lIcVBuCzzLcmux2rbfQ',
    appId: '1:1038018450510:web:b814d9ed89c33b3f61df1f',
    messagingSenderId: '1038018450510',
    projectId: 'fire-alert-system-b2619',
    authDomain: 'fire-alert-system-b2619.firebaseapp.com',
    storageBucket: 'fire-alert-system-b2619.firebasestorage.app',
    measurementId: 'G-H1Q1TLWRHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2iFgSc2nw3-eeH_5jKgHcPwsTUbRk6w',
    appId: '1:1038018450510:android:2fbf1b478d6f1eca61df1f',
    messagingSenderId: '1038018450510',
    projectId: 'fire-alert-system-b2619',
    storageBucket: 'fire-alert-system-b2619.firebasestorage.app',
  );
}
