// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUHK46eQpWkrXzTwIqpbKYHA8d4BjMEME',
    appId: '1:720743481934:web:8646ab0fae453471b8b91f',
    messagingSenderId: '720743481934',
    projectId: 'fire-alert-system-c01eb',
    authDomain: 'fire-alert-system-c01eb.firebaseapp.com',
    storageBucket: 'fire-alert-system-c01eb.firebasestorage.app',
    measurementId: 'G-TK7B5XTDGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdMfoLBUFl_R-5TdKuQTNmlgGK9dAWtE',
    appId: '1:720743481934:android:3858a89dba1e6d77b8b91f',
    messagingSenderId: '720743481934',
    projectId: 'fire-alert-system-c01eb',
    storageBucket: 'fire-alert-system-c01eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufBH9VA0Vi4_speY0nv205x44zVOPVUI',
    appId: '1:720743481934:ios:863f81fe462bf568b8b91f',
    messagingSenderId: '720743481934',
    projectId: 'fire-alert-system-c01eb',
    storageBucket: 'fire-alert-system-c01eb.firebasestorage.app',
    iosBundleId: 'com.firealert.system.fireAlertSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufBH9VA0Vi4_speY0nv205x44zVOPVUI',
    appId: '1:720743481934:ios:863f81fe462bf568b8b91f',
    messagingSenderId: '720743481934',
    projectId: 'fire-alert-system-c01eb',
    storageBucket: 'fire-alert-system-c01eb.firebasestorage.app',
    iosBundleId: 'com.firealert.system.fireAlertSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUHK46eQpWkrXzTwIqpbKYHA8d4BjMEME',
    appId: '1:720743481934:web:7ee4f0467dee75c7b8b91f',
    messagingSenderId: '720743481934',
    projectId: 'fire-alert-system-c01eb',
    authDomain: 'fire-alert-system-c01eb.firebaseapp.com',
    storageBucket: 'fire-alert-system-c01eb.firebasestorage.app',
    measurementId: 'G-0Q9Q57EJH7',
  );
}
